apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: kube-mpenv-com-tls
spec: 
  # The secret that is stored with the Certificate.
  secretName: kube-mpenv-com
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kube.mpenv.com
  dnsNames:
    - kube.mpenv.com
    - www.kube.mpenv.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - 
