# Issuer config file for letsencrypt
# Using a custom api 
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
# Reach out to the production version of letsencrypt
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Hardcoded Url to reach out to for generating certific
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'muzammilhmomin@gmail.com'
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}