# Issuer config file for letsencrypt.
# Using a custom api .
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
# Reach out to the production version of letsencrypt.
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Hardcoded Url to reach out to for generating certificates.
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email not used for any verification purposes , used by letsencrypt to contact.
    email: 'muzammilhmomin@gmail.com'
    # LetsEncrypt sends a secret key for verification purposes; we do not use it anywhere
    privateKeySecretRef:
      name: letsencrypt-prod
    # Tells LetsEncrypt to use the http method for verification process . Alternate option 
    http01: {}